Began work on setting up the admin permissions using Devise Authoriza…
AbbyMB/VenViews pull request #9
Opened 2018-10-17 20:26 UTC by abigail29

Began work on setting up the admin permissions using Devise Authorization!  Thank you!

2018-10-17 21:07 UTC, bkincart requested changes

2018-10-17 21:07 UTC, bkincart commented on app/controllers/venues_controller.rb
> +  end
FYI the way you have this set up, only an admin will be able to see the venues index or show page. Is that what you were going for?

2018-10-17 21:07 UTC, bkincart commented on db/seeds.rb
> +Venue.create!( name: 'Hatch Shell', address: '47 David G Mugar Way', description: 'The HALF shell', capacity: 500, url: 'http://www.hatchshell.com/' )
Please indent!

2018-10-17 21:07 UTC, bkincart commented on app/models/user.rb
> +    end
You should add some validations for the role here: probably a presence validation, plus an inclusion validation to make sure it's one of the valid role types

2018-10-17 21:07 UTC, bkincart commented on app/models/user.rb
> +    end
You should also add tests for this!

2018-10-18 18:42 UTC, abigail29 commented
This is the updated admin permissions one.  Let me know if anything else is wrong! thank you!

2018-10-18 20:47 UTC, bkincart approved these changes

2018-10-18 20:52 UTC, merged